#!/bin/sh
# Cross-platform NFS server setup (FreeBSD / Linux)
# Usage: ./setup_nfs_server.sh /export/dir client1 [client2 ...]

set -e

# --- Usage check first ---
if [ $# -lt 2 ]; then
    echo "Usage: $0 EXPORT_DIR client1 [client2 ...]"
    exit 1
fi

EXPORT_DIR=${1:-/mnt/nfs_mem}
shift
CLIENTS="$@"
EXPORT_SIZE=6G          # default volumn size

echo ">>> Setting up NFS export: ${EXPORT_DIR} for clients: ${CLIENTS}"

# Detect OS
OS=$(uname)
echo ">>> Detected OS: $OS"

# Ensure export directory exists
mkdir -p "${EXPORT_DIR}"

# OS-specific setup
if [ "$OS" = "FreeBSD" ]; then
    echo ">>> Using FreeBSD NFS setup"
    
    # Load tmpfs if needed
    kldstat -m tmpfs >/dev/null 2>&1 || kldload tmpfs
    
    # Mount tmpfs
    mount -t tmpfs -o size="${EXPORT_SIZE}" tmpfs "${EXPORT_DIR}"
    
    # Build /etc/exports
    {
        echo "# Auto-generated by setup_nfs_server.sh"
        echo "V4: /"
        printf "%s -maproot=root" "${EXPORT_DIR}"
        for c in ${CLIENTS}; do
            printf " %s" "${c}"
        done
        echo
    } > /etc/exports
    
    # Enable and restart services
    sysrc nfs_server_enable=YES
    sysrc mountd_enable=YES
    sysrc rpcbind_enable=YES
    service rpcbind restart
    service mountd restart
    service nfsd restart

    echo ">>> NFS server ready. Exports:"
    showmount -e

elif [ "$OS" = "Linux" ]; then
    echo ">>> Using Linux NFS setup"

    # tmpfs is builtin, no need to modprobe
    # Mount tmpfs
    mount -t tmpfs -o size="${EXPORT_SIZE}" tmpfs "${EXPORT_DIR}" || true

    # Write /etc/exports (Linux)
    {
      echo "# Auto-generated by setup_nfs_server.sh"
      printf "%s" "${EXPORT_DIR}"
      for c in ${CLIENTS}; do
          printf " %s(rw,sync,no_subtree_check)" "${c}"
      done
      echo
    } > /etc/exports

    # Restart NFS service: detect correct service name
    if systemctl list-units --type=service | grep -q nfs-kernel-server; then
        systemctl restart nfs-kernel-server
    elif systemctl list-units --type=service | grep -q nfs-server; then
        systemctl restart nfs-server
    else
        echo "!!! Could not find NFS service to restart. Please install nfs-utils or nfs-kernel-server."
    fi

    # Re-export shares
    exportfs -ra

    echo ">>> NFS server ready. Exports:"
    exportfs -v
else
    echo "!!! Unsupported OS: $OS"
    exit 1
fi

df -h "${EXPORT_DIR}"