#!/bin/sh
# Cross-platform NFS server setup (FreeBSD / Linux)
# Usage: ./setup_nfs_server.sh /export/dir client1 [client2 ...]

set -e

# --- Usage check first ---
if [ $# -lt 2 ]; then
    echo "Usage: $0 EXPORT_DIR client1 [client2 ...]"
    echo "Exampe: $0 /mnt/nfs_mem r1"
    exit 1
fi

EXPORT_DIR=${1:-/mnt/nfs_mem}
shift
CLIENTS="$@"
EXPORT_SIZE=6G          # default volumn size

# Detect node type (Linux/FreeBSD specific path, fallback unknown)
if [ -x /usr/libexec/emulab/nodetype ]; then
    NODE_TYPE=$(/usr/libexec/emulab/nodetype)
elif [ -x /usr/local/etc/emulab/nodetype ]; then
    NODE_TYPE=$(/usr/local/etc/emulab/nodetype)
else
    NODE_TYPE="unknown"
    echo ">>> Warning: nodetype command not found, using 'unknown'"
fi

echo ">>> Setting up NFS export: ${EXPORT_DIR} for clients: ${CLIENTS}"

# Detect OS
OS=$(uname)
echo ">>> Detected OS: $OS"

# Ensure export directory exists
mkdir -p "${EXPORT_DIR}"

# OS-specific setup
if [ "$OS" = "FreeBSD" ]; then
    echo ">>> Using FreeBSD NFS setup"
    
    # Load tmpfs if needed
    kldstat -m tmpfs >/dev/null 2>&1 || kldload tmpfs
    
    # Mount tmpfs
    mount -t tmpfs -o size="${EXPORT_SIZE}" tmpfs "${EXPORT_DIR}"
    
    # Build /etc/exports
    {
        echo "# Auto-generated by setup_nfs_server.sh"
        echo "V4: /"
        printf "%s -maproot=root" "${EXPORT_DIR}"
        for c in ${CLIENTS}; do
            printf " %s" "${c}"
        done
        echo
    } > /etc/exports
    
    # Enable and restart services
    sysrc nfs_server_enable="YES"
    sysrc nfsv4_server_enable="YES"
    sysrc nfs_server_flags="-t -n 8"
    sysrc mountd_enable="YES"
    sysrc rpcbind_enable="YES"
    service rpcbind restart
    service mountd restart
    service nfsd restart

    echo ">>> NFS server ready. Exports:"
    showmount -e

elif [ "$OS" = "Linux" ]; then
    echo ">>> Using Linux NFS setup"

    # tmpfs is builtin, no need to modprobe
    # Mount tmpfs
    mount -t tmpfs -o size="${EXPORT_SIZE}" tmpfs "${EXPORT_DIR}" || true

    # Write /etc/exports (Linux)
    {
      echo "# Auto-generated by setup_nfs_server.sh"
      printf "%s" "${EXPORT_DIR}"
      for c in ${CLIENTS}; do
          printf " %s(rw,sync,no_subtree_check)" "${c}"
      done
      echo
    } > /etc/exports

    # Restart NFS service: detect correct service name
    if systemctl list-units --type=service | grep -q nfs-kernel-server; then
        systemctl restart nfs-kernel-server
    elif systemctl list-units --type=service | grep -q nfs-server; then
        systemctl restart nfs-server
    else
        echo "!!! Could not find NFS service to restart. Please install nfs-utils or nfs-kernel-server."
    fi

    # Re-export shares
    exportfs -ra

    echo ">>> NFS server ready. Exports:"
    exportfs -v
else
    echo "!!! Unsupported OS: $OS"
    exit 1
fi

df -h "${EXPORT_DIR}"

log_name="${EXPORT_DIR}/${NODE_TYPE}_nfs_server.info"

uname -v | tee ${log_name}
sysctl net.inet.tcp.functions_default | tee -a ${log_name}
# Don't cache ssthresh from previous connection
sysctl net.inet.tcp.hostcache.enable=0 | tee -a ${log_name}
# force to close the control socket after 4 seconds
sysctl net.inet.tcp.msl=2000 | tee -a ${log_name}
sysctl net.inet.tcp.cc.algorithm | tee -a ${log_name}
